@startuml Prueba
autonumber
actor Usuario as u
boundary requests.routes as rr
boundary requests_page.ejs as rpe
boundary consult_requests_logic.ejs as crl
control requests.controller as rc
entity requests.model as rm
database Nebula as db

activate u
u -> rr : GET /requests
deactivate u

activate rr
rr -> rc : get_requests()
deactivate rr
activate rc
rc -> rpe : response.render('requests_page.ejs)
deactivate rc
activate rpe 
rpe -> u : HTML requests_page.ejs
deactivate rpe
activate u
u ->> rr : get_info() / fetch('/requests/Requests', POST)
activate rr
rr ->> rc : get_collabs_requests()
deactivate rr
activate rc
rc ->> rm : fetchRequests(request.session.email, offset, filter)
activate rm
rm ->> db : get_team_requests()
activate db
db -->> rm : [data] 
deactivate db
rm -->> rc : [data]
deactivate rm
rc -->> crl : [data]
rc -->> u : XML HTML
deactivate rc

u ->> u : format_data_to_json
u -> u : createTableRequests(data)
u -> u : table.innerHTML = table_content
deactivate rpe

@enduml