
@startuml REQ_27
autonumber
actor SuperAdmin as S
boundary general.routes.json as Route
boundary register_followUp.ejs as Register
control register.controller.js as SController
entity SuperAdmin.model as SModel
database Nebula as db

activate S
S -> Route : POST /follow_ups
deactivate S

activate Route
Route -> SController : POST 
deactivate Route

activate SController
SController -> SModel : getRequests()
deactivate SController

@enduml