@startuml Prueba
autonumber
actor Collaborator
boundary general.route.js as gRoutes
boundary home_page.ejs as homeView
control home.controller.js as homeController
entity request.model as absModel
database nebula as neb

activate Collaborator
Collaborator -> gRoutes : GET/
deactivate Collaborator

activate gRoutes
gRoutes -> homeController: get_home()
deactivate gRoutes

activate homeController
homeController ->> absModel: get_home_total_abs()

activate absModel
absModel ->> neb: (SELECT * FROM solicitudesFalta)>\n <(SELECT * FROM dias_solicitud)

activate neb
neb-->> absModel: [status, type, fistDate, lastDate]
deactivate neb

absModel -->> homeController: [{stats, type, fistDate, lastDate}]
homeController -> homeController: calculate_abs()
deactivate absModel

homeController -->> homeView: response

deactivate homeController



activate homeView
homeView -> Collaborator: html
deactivate homeView

activate Collaborator
deactivate Collaborator


@enduml