@startuml REQ_7
autonumber
actor Collaborator as C 
boundary general.routes.json as Route
boundary home.ejs as home
control home.controller.js as HController
actor GoogleAPI as GoogleApi


activate C
C ->> Route : GET /
deactivate C 

activate Route
Route -->> HController : get_home()
deactivate Route

activate HController
HController -->> GoogleApi : calendar.calendarList.list()
deactivate HController

note right of GoogleApi :  const calendarListResponse = await calendar.calendarList.list(); \nconst calendars = calendarListResponse.data.items;\n let eventos = [];\n\n for (const cal of calendars) {\n const calendarId = cal.id;\nconst eventsResponse = await calendar.events.list({\ncalendarId,\n singleEvents: true,\n orderBy: 'startTime'\n});\n const eventosDelCalendario = eventsResponse.data.items.map(event => ({\n title: event.summary,\n  start: event.start.dateTime || event.start.date,\n end: event.end?.dateTime || event.end?.date,\n backgroundColor: cal.backgroundColor,\nborderColor : cal.backgroundColor,\ndisplay: 'block',\n color: '#FFFF',\ndescription: event.description,\n}));\neventos = eventos.concat(eventosDelCalendario);\n}

activate GoogleApi
GoogleApi -->> HController : eventos
deactivate GoogleApi

activate HController
HController --> home : response.render ("home_page", { diasDisponibles, diasTotales, error,\n permissions: request.session.permissions,total_absences: absences.length,\n csrfToken: request.csrfToken(),  eventos})
deactivate HController

activate home
home -->> C : HTML calendar
deactivate home

@enduml
