@startuml Diseño_Ausencias 
autonumber 
actor Collaborator 
boundary general.route.js as gRoutes 
boundary home_page.ejs as homeView 
control home.controller.js as homeController 
entity requests.model.js as requestsModel 
database nebula as DB 

Collaborator -> gRoutes : GET / 

activate gRoutes 
gRoutes -> homeController : get_home() 
deactivate gRoutes 
activate homeController 
homeController ->> requestsModel : fetchDaysApproved(request.session.email) 
activate requestsModel 
requestsModel ->> DB : `SELECT ds.fecha \n FROM solicitudes_falta sf \n INNER JOIN dias_solicitados ds \n ON sf.id_solicitud_falta = ds.id_solicitud_falta \n INNER JOIN colaborador c \n ON c.id_colaborador = sf.id_colaborador \n WHERE c.email = ? AND sf.estado = 1; \n `, [email]) 
activate DB 
DB -->> requestsModel : [fechas aprobadas] 
deactivate DB 
requestsModel -->> homeController : [fechas aprobadas] 
deactivate requestsModel 
homeController -->> homeView :  response.render("home_page", { \n total_absences: absences.length,}) 
deactivate homeController 
activate homeView 
homeView --> Collaborator : HTML 
deactivate homeView 
activate Collaborator 
@enduml