@startuml Prueba
autonumber
actor Collaborator
boundary general.route.js as gRoutes
boundary total_days_of_absence.ejs as absView
control total_days_of_absence.controller.js as absController
entity request.model as absModel
database nebula as neb

activate Collaborator
Collaborator -> gRoutes : GET/
deactivate Collaborator

activate gRoutes
gRoutes -> absController: get_home()
deactivate gRoutes

activate absController
absController ->> absModel: get_home_total_abs()

activate absModel
absModel ->> neb: (SELECT * FROM solicitudesFalta)>\n <(SELECT * FROM dias_solicitud)

activate neb
neb-->> absModel: [status, type, fistDate, lastDate]
deactivate neb

absModel -->> absController: [{stats, type, fistDate, lastDate}]
absController -> absController: calculate_abs()
deactivate absModel

absController -->> absView: response

deactivate absController



activate absView
absView -> Collaborator: html
deactivate absView

activate Collaborator
deactivate Collaborator


@enduml