@startuml REQ-29
autonumber
actor superAdmin
boundary saveSucces.ejs as saveSucces

boundary general.routes.js as generalRoute
boundary collabs.routes.js as collabsRoute

boundary collabs.ejs as CollabsView
control collabs.controller.js as collabsController

activate superAdmin
superAdmin -> generalRoute : GET/view_collabs
deactivate superAdmin
activate generalRoute

generalRoute -> collabsRoute: collabs_routes
deactivate generalRoute
activate collabsRoute

collabsRoute -> collabsController: get_collabs(request, response)
deactivate collabsRoute
activate collabsController

database Nebula as nebula
entity Collaborator as collabModel
entity Department as depModel
entity Company as companyModel
entity Role as roleModel

collabsController ->> depModel: fetchAllDep()
activate depModel
depModel ->> nebula: execute(SELECT DISTINCT id_departamento, nombre_departamento FROM departamento ORDER BY nombre_departamento ASC)
activate nebula
nebula -->> depModel: rowsDep
deactivate nebula
depModel -->> collabsController: rowsDep
deactivate depModel

collabsController ->> companyModel: fetchAllEmp()
activate companyModel
companyModel ->> nebula: execute(SELECT DISTINCT nombre_empresa FROM empresa ORDER BY nombre_empresa ASC)
activate nebula
nebula -->> companyModel: rowsEmp
deactivate nebula
companyModel -->> collabsController: rowsEmp
deactivate companyModel

collabsController ->> roleModel: fetchAllRol()
activate roleModel
roleModel ->> nebula: execute(SELECT DISTINCT id_rol FROM rol ORDER BY id_rol ASC)
activate nebula
nebula -->> roleModel: rowsRol
deactivate nebula
roleModel -->> collabsController: rowsRol
deactivate roleModel

collabsController ->> collabModel: fetchAllColabPues(), fetchAllColabMod()
activate collabModel
collabModel ->> nebula: execute(SELECT DISTINCT puesto FROM colaborador ORDER BY puesto ASC); \n execute(SELECT DISTINCT modalidad FROM colaborador ORDER BY modalidad ASC); 
activate nebula

nebula -->> collabModel: rowsColP,rowsColM

collabModel -->> collabsController: rowsColP,rowsColM
deactivate collabModel

collabsController -> CollabsView: response.render('collabs.ejs', {...settings, permissions: request.session.permissions,\n csrfToken: request.csrfToken(),puesto: rowsColP, modalidad: rowsColM,\n empresa: rowsEmp,departamento: rowsDep,rol: rowsRol,successData});)
deactivate collabsController
activate CollabsView

CollabsView -> superAdmin: HTML
deactivate CollabsView
activate superAdmin

superAdmin -> saveSucces: response.render('saveSucces.ejs')
deactivate collabsController
activate saveSucces
deactivate superAdmin

saveSucces -> generalRoute : POST/view_collabs
deactivate superAdmin
activate generalRoute
deactivate saveSucces

generalRoute -> collabsRoute: collabs_routes
deactivate generalRoute
activate collabsRoute

collabsRoute -> collabsController: post_collabs(request, response)
deactivate collabsRoute
activate collabsController

create entity new_Equipo as equipobM
collabsController -> equipobM: new Equipo(idcolab, request.body.id_departamento, request.body.id_rol)
activate equipobM
collabsController ->> equipobM: save( )
equipobM -> nebula: execute('INSERT INTO equipo (id_colaborador, id_rol, id_departamento) VALUES(?,?,?)', \n [id_colaborador, this.id_r, this.id_dep])
activate nebula

nebula -->> equipobM: Query ok
deactivate nebula

equipobM -->> collabsController: promesa
deactivate equipobM


create entity new_Colab as collabM
entity Collaborator as collabModel

collabsController -> collabM: new Collaborator(password, request.body.nombre, request.body.apellidos, request.body.fechaNacimiento,  \n request.body.telefono, request.body.puesto, request.body.email, request.body.fechaIngreso, \n request.body.ubicacion, request.body.modalidad, request.body.curp, request.body.rfc)
activate collabM

collabsController ->> collabM: save( )
database Nebula as nebula

collabM -> nebula: execute(`INSERT INTO collaborator (id_colaborador, nombre, apellidos, fechaNacimiento, \n telefono, puesto, email, contrasena, fechaIngreso, ubicacion, modalidad, curp, rfc) \n VALUES (UUID(), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, \n [this.nombre, this.apellidos, this.fechaNacimiento, this.telefono,\n this.puesto, this.email, password, this.fechaIngreso, this.ubicacion,\n this.modalidad, this.curp, this.rfc])
activate nebula

nebula -->> collabM: Query ok
deactivate nebula

collabM -->> collabsController: promesa
deactivate collabM

collabsController -> CollabsView: response.redirect("/view_collabs")
deactivate collabsController
activate CollabsView

CollabsView -> superAdmin: HTML
deactivate saveSucces
activate superAdmin
deactivate CollabsView

@enduml