@startuml REQ-29
autonumber
actor superAdmin
boundary general.routes.js as generalRoute
boundary collabs.routes.js as collabsRoute

boundary collabs.ejs as CollabsView
boundary saveSucces.ejs as saveSucces
control collabs.controller.js as collabsController
entity collab.model as collabModel
database Nebula as nebula

activate superAdmin
superAdmin -> generalRoute : GET/view_collabs
deactivate superAdmin
activate generalRoute

generalRoute -> collabsRoute: collabs_routes
deactivate generalRoute
activate collabsRoute

collabsRoute -> collabsController: get_collabs(request, response)
deactivate collabsRoute
activate collabsController

collabsController -> nebula: fetchAll()
deactivate collabsController
activate nebula

nebula --> collabsController: response.render('collabs.ejs')
deactivate nebula

collabsController -> CollabsView: response.render

CollabsView -> superAdmin: HTML

superAdmin -> generalRoute : POST/view_collabs

superAdmin -> collabsRoute: POST/addCollabs
deactivate superAdmin
activate generalRoute

generalRoute -> collabsRoute: collabs_routes
deactivate generalRoute
activate collabsRoute

collabsRoute -> collabsController: post_collabs

collabsController -> collabModel: new Model(request.body.valor)
' activate collabModel

collabModel -> nebula: execute("INSERT INTO Modelo(?)", this.valor)
' activate nebula

nebula -->> collabModel: Query ok
' deactivate nebula

collabModel -->> collabsController: promesa
' deactivate collabModel

collabsController -> saveSucces: response.render
' deactivate collabsController
' activate saveSucces

saveSucces -> superAdmin: HTML
' deactivate saveSucces
' activate superAdmin
' deactivate superAdmin

@enduml